---
title: "First Knit"
author: "Cleo Ware"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended 2 different high schools. The first was Foothill high school in Sacramento CA. The second was Palmdale high school. And yes, I did graduate. I find English to be much easier for me then Math. I've never really been a fan of math. The subject I do best in is history. I find learning about history fascinating.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
 My home computer is an Apple IMac. I would rate my computer skills at a 6. My internet connection where i live is ok. It's not super fast. However, it's not super slow. 
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I prefer to be called Cleo by my classmates. I don't really have anything else I would rather be called. Cleo works just fine for me...  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I have many things I'd like to achieve in life. For starters, I want to graduate college. Then eventually become a lawyer. I'd like to retire while still fairly young then travel the world. And eventually have some grandkids. Once I'm older.   
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
I've been blessed enough to have traveled to several different countries including France, Italy, UK, Jamaica, and Canada. No, I've never been in the military. If I got drafted the branch I'd choose would be Air Force. This woulbe be my choice because I'd like to be a figter  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




